#![feature(os_string_truncate)]

// notes:
// 170k relocs total
//
//
// 100k relocs in text
//
// 16k function relocs in text
// 4k exact function relocs in text
//
// 41k const relocs in text

use std::collections::{btree_map, BTreeMap, HashMap};

use capstone::arch::x86::{ArchMode, ArchSyntax, X86Operand, X86OperandType};
use capstone::arch::ArchOperand;
use capstone::prelude::{BuildsCapstone, BuildsCapstoneSyntax};
use capstone::Capstone;
use capstone::InsnGroupType::*;

use object::read::pe::PeSection;
use object::LittleEndian;
use object::{Object, ObjectSection, SectionKind};

use pdb2::{FallibleIterator, RawString};

const EXECUTABLE: &[u8] = include_bytes!("../resources/survarium.exe");
const DEBUG_SYMBOLS: &[u8] = include_bytes!("../resources/survarium.pdb");

pub struct ObjectFiles<'a> {
    pub objects: HashMap<&'a [u8], ObjectFile>,
}

pub struct ObjectFile {
    pub object: object::write::Object<'static>,
    pub data_section_id: object::write::SectionId,
    pub rdata_section_id: object::write::SectionId,
    pub text_section_id: object::write::SectionId,
}

// Address - Offset from the beginning of executable
// Offset  - Offset from a certain section
// Rva     - Offset from ImageBase (correct?)

#[derive(Clone, Debug, Default, Copy)]
pub struct SecInfo<'a> {
    pub rva: usize,
    pub size: usize,
    pub id: u16,

    pub address: usize,
    pub data: &'a [u8],
}

// # Notes
//
// ## 1. On object file structure
//
// 1. The file structure is based on `source_path` from PDB files.
// 2. This information is available for all functions not generated by the compiler
//    (the logic for when it's missing from compiler-generated functions is unclear).
// 3. Compiler generated functions are stored in the `msvc_internal/functions` folder.
// 4. This might be split further in the future.
//
//
// ## 2. Mangled symbols search
//
// 1. There is no direct mapping (at least, I don't know of any) from unmangled symbols
//    to mangled symbols stored in another table in PDB files.
// 2. To solve this problem approximations are used.
// 3. Specifically, take a look at `find_closest_symbol` function, which tries to find
//    a "similar function". If it fails, it chooses the shortest option available.
// 4. For half of the functions a "similar function" is found. But I don't know what it
//    it means exactly in the generated object files.
//
//
// ## 3. Jump symbols
//
// 1. They suffer the same problem as mangled symbols search.
// 2. It would be a good assumption to jump to a function in the same class.
// 3. Which is currently not what is happening. This can be implemented with `msvc_demangler`
//    crate, which allows parsing mangled functions to exact class and namespace names.
//
//
// ## 4. sushi@TODO: Start discussion in object crate
// ## 6. sushi@TODO: Relocations in .data and .rdata
// ## 7. sushi@TODO: Initialized statics in .rdata
//
//
// ## 8. sushi@TODO: Better parsing.
//
// 1. While not important right now, we need to be able to generate object files for specific
//    targets. This way it is easier to see progress for code related to multiplayer.
// 2. Those targets would need to cover only certain namespaces (vostok, survarium, bullet
//    functions)
//
//
// ## 9. sushi@TODO: CMD tool.
//
// 1. Command line arguments need to be added (with clap).
// 2. We need to distinguish `target` and `base` executables. `base` executables should try to
//    use the same symbols `target` is using (when possible during disambiguation) for closer
//    assembly matches.

fn main() -> anyhow::Result<()> {
    let exe = object::read::pe::PeFile32::parse(EXECUTABLE)?;
    let pdb = pdb2::PDB::open(std::io::Cursor::new(DEBUG_SYMBOLS))?;

    process_executable(exe, pdb)?;

    Ok(())
}

fn process_executable<S: pdb2::Source<'static> + 'static>(
    exe: object::read::pe::PeFile32<'static>,
    pdb: pdb2::PDB<'static, S>,
) -> anyhow::Result<()> {
    let exe: &'static object::read::pe::PeFile32 = leak(exe);

    let object_files = ObjectFiles::parse(exe, pdb)?;
    object_files.write(std::path::Path::new("objdiff/target"))?;

    Ok(())
}

impl ObjectFiles<'static> {
    fn parse<S: pdb2::Source<'static> + 'static>(
        exe: &'static object::read::pe::PeFile32<'static>,
        mut pdb: pdb2::PDB<'static, S>,
    ) -> anyhow::Result<ObjectFiles<'static>> {
        let image_base = exe
            .nt_headers()
            .optional_header
            .image_base
            .get(LittleEndian);

        let dbi = leak(pdb.debug_information()?);
        let string_table: &'static pdb2::StringTable<'static> = leak(pdb.string_table()?);

        let build_sec_info = |sec: PeSection<'static, 'static, _>| {
            Ok::<_, anyhow::Error>(SecInfo {
                rva: sec.address() as usize - image_base as usize,
                size: sec.size() as usize,
                id: sec.index().0 as u16,

                address: sec.address() as usize,
                data: sec.data()?,
            })
        };

        let Some(text_sec) = exe.section_by_name(".text") else {
            anyhow::bail!("Missing .text section");
        };
        let Some(rdata_sec) = exe.section_by_name(".rdata") else {
            anyhow::bail!("Missing .rdata section");
        };
        let Some(data_sec) = exe.section_by_name(".data") else {
            anyhow::bail!("Missing .data section");
        };

        let text = build_sec_info(text_sec)?;
        let rdata = build_sec_info(rdata_sec)?;
        let data = build_sec_info(data_sec)?;

        //
        // rva, offset, address
        //

        let mut functions = BTreeMap::<usize, Vec<RawString>>::new();
        let mut statics = BTreeMap::<usize, RawString>::new();
        let mut strings = BTreeMap::<usize, (RawString, Vec<u8>)>::new();

        {
            let symbol_table: &'static pdb2::SymbolTable = leak(pdb.global_symbols()?);

            // Additional non-mangled constants from `Data` symbols.
            // Only used for symbols not found in `Public` symbols.
            // (@NOTE: might be useless, we will see)
            let mut data_statics = vec![];

            let mut symbols = symbol_table.iter();
            while let Some(symbol) = symbols.next()? {
                match symbol.parse() {
                    Ok(pdb2::SymbolData::Public(pdb2::PublicSymbol {
                        function,
                        offset,
                        name,
                        ..
                    })) if function => {
                        assert_eq!(offset.section, text.id);

                        let offset = offset.offset as usize;

                        functions.entry(offset).or_default().push(name);
                    }

                    Ok(pdb2::SymbolData::Public(pdb2::PublicSymbol { offset, name, .. }))
                        if offset.section == rdata.id && name.as_bytes().starts_with(b"??_C@_") =>
                    {
                        let offset = offset.offset as usize;

                        let msvc_demangler::Type::ConstantString(string) =
                            msvc_demangler::parse(&name.to_string())?.symbol_type
                        else {
                            continue;
                        };

                        let result = strings.insert(offset, (name, string));
                        assert_eq!(result, None);
                    }

                    Ok(pdb2::SymbolData::Public(pdb2::PublicSymbol { offset, name, .. }))
                        if offset.section == data.id =>
                    {
                        let offset = offset.offset as usize;

                        let old_value = statics.insert(offset, name);
                        if let Some(value) = old_value {
                            anyhow::bail!(
                                "Conflict at offset {offset:x?} between '{value}' and '{name}'"
                            );
                        }
                    }

                    // Ignored for now.
                    // There are not that many symbols and the ones with types are either U64 or F80.
                    Ok(pdb2::SymbolData::Data(pdb2::DataSymbol { offset, .. }))
                        if offset.section == rdata.id => {}

                    // in public they are mangled
                    // in data all symbols are not mangled, yes
                    Ok(pdb2::SymbolData::Data(pdb2::DataSymbol { offset, name, .. }))
                        if offset.section == data.id =>
                    {
                        let offset = offset.offset as usize;

                        data_statics.push((offset, name));
                    }
                    _ => {}
                }
            }

            for (offset, name) in data_statics {
                let entry = statics.entry(offset);
                match entry {
                    btree_map::Entry::Vacant(entry) => {
                        entry.insert(name);
                    }
                    _ => (),
                }
            }
        };

        {
            let mut modules = dbi.modules()?;

            while let Some(module) = modules.next()? {
                let Some(module_info) = pdb.module_info(&module)? else {
                    continue;
                };
                let module_info = leak(module_info);

                let mut iter = module_info.symbols()?;

                while let Some(symbol) = iter.next()? {
                    let (name, offset) = match symbol.parse() {
                        Ok(pdb2::SymbolData::Procedure(pdb2::ProcedureSymbol {
                            name,
                            offset,
                            ..
                        })) => (name, offset),
                        Ok(pdb2::SymbolData::Thunk(pdb2::ThunkSymbol { offset, name, .. })) => {
                            (name, offset)
                        }
                        _ => continue,
                    };

                    match functions.entry(offset.offset as usize) {
                        btree_map::Entry::Vacant(entry) => {
                            entry.insert(vec![name]);
                        }
                        _ => (),
                    }
                }
            }
        }

        //
        // Fix all relocations in the text section of the executable.
        // @NOTE: They can be in other parts
        //

        enum RelocKind<'a> {
            // .text
            Function {
                overloads: &'a [RawString<'static>],
            },

            // .rdata
            ConstantString {
                symbol: RawString<'static>,
                data: &'a [u8],
            },
            ConstantValue {
                data: [u8; 4], // first 4 bytes
            },

            // .data
            // @TODO: Distinguish uninit vs. init statics
            Static {
                symbol: RawString<'static>,
            },
        }

        let mut text_sec_data = text.data.to_vec();
        let mut text_relocs = BTreeMap::<usize, RelocKind>::new();

        let Some(reloc_sec) = exe.section_by_name(".reloc") else {
            anyhow::bail!("Missing .reloc section");
        };

        {
            #[repr(C)]
            #[derive(bytemuck::AnyBitPattern, bytemuck::NoUninit, Copy, Clone)]
            struct RelocHeader {
                page_rva: u32,
                block_size: u32,
            }
            const HEADER_SIZE: usize = std::mem::size_of::<RelocHeader>();

            #[repr(C)]
            #[derive(bytemuck::AnyBitPattern, bytemuck::NoUninit, Copy, Clone)]
            struct RelocEntry {
                entry: u16,
            }

            let mut pos = 0;
            let reloc_data = reloc_sec.data()?;
            while pos + HEADER_SIZE <= reloc_data.len() {
                let RelocHeader {
                    page_rva,
                    block_size,
                } = bytemuck::pod_read_unaligned(&reloc_data[pos..pos + HEADER_SIZE]);

                if block_size == 0 || block_size < 8 {
                    break;
                }

                let entries: &[RelocEntry] =
                    bytemuck::cast_slice(&reloc_data[pos + HEADER_SIZE..pos + block_size as usize]);
                pos += block_size as usize;

                for RelocEntry { entry } in entries {
                    let reloc_type = entry >> 12;
                    let reloc_offset = entry & 0x0FFF;

                    const RELOC_TYP_HIGHLOW: u16 = 3;

                    if reloc_type != RELOC_TYP_HIGHLOW {
                        continue;
                    }

                    let reloc_rva = (page_rva + u32::from(reloc_offset)) as usize;
                    let in_text = (text.rva..text.rva + text.size).contains(&reloc_rva);

                    // this is that "cornercase"
                    if !in_text {
                        continue;
                    }

                    let offset_in_text = (reloc_rva - text.rva) as usize;
                    let target_va: u32 = bytemuck::pod_read_unaligned(
                        &text_sec_data[offset_in_text..offset_in_text + 4],
                    );
                    let target_va = target_va as usize;

                    match () {
                        () if (text.address..text.address + text.size).contains(&target_va) => {
                            let target_offset_in_text = target_va - text.address;

                            let (function_offset_in_text, function_names) = functions
                                .range(..=target_offset_in_text)
                                .next_back()
                                .expect("all function relocs to be named");

                            text_sec_data[offset_in_text..offset_in_text + 4].copy_from_slice(
                                &u32::to_le_bytes(
                                    (target_offset_in_text - *function_offset_in_text) as u32,
                                ),
                            );
                            text_relocs.insert(
                                offset_in_text,
                                RelocKind::Function {
                                    overloads: function_names,
                                },
                            );
                        }
                        () if (rdata.address..rdata.address + rdata.size).contains(&target_va) => {
                            let target_offset_in_rdata = target_va - rdata.address;

                            match strings.range(..=target_offset_in_rdata).next_back() {
                                Some((string_offset_in_rdata, (string_mangled_name, string)))
                                    if target_offset_in_rdata - string_offset_in_rdata
                                        < string.len() =>
                                {
                                    text_sec_data[offset_in_text..offset_in_text + 4]
                                        .copy_from_slice(&u32::to_le_bytes(
                                            (target_offset_in_rdata - *string_offset_in_rdata)
                                                as u32,
                                        ));

                                    text_relocs.insert(
                                        offset_in_text,
                                        RelocKind::ConstantString {
                                            symbol: *string_mangled_name,
                                            data: string,
                                        },
                                    );
                                }
                                _ => {
                                    text_relocs.insert(
                                        offset_in_text,
                                        RelocKind::ConstantValue {
                                            data: bytemuck::pod_read_unaligned(
                                                &rdata.data[target_offset_in_rdata
                                                    ..target_offset_in_rdata + 4],
                                            ),
                                        },
                                    );
                                }
                            };
                        }
                        () if (data.address..data.address + data.size).contains(&target_va) => {
                            let target_offset_in_data = target_va - data.address;

                            let (static_offset_in_data, static_name) = statics
                                .range(..=target_offset_in_data)
                                .next_back()
                                .expect("all statics relocs to be named");

                            text_sec_data[offset_in_text..offset_in_text + 4].copy_from_slice(
                                &u32::to_le_bytes(
                                    (target_offset_in_data - *static_offset_in_data) as u32,
                                ),
                            );
                            text_relocs.insert(
                                offset_in_text,
                                RelocKind::Static {
                                    symbol: *static_name,
                                },
                            );
                        }
                        () => (),
                    }
                }
            }
        }

        let mut object_files = ObjectFiles {
            objects: HashMap::new(),
        };
        {
            let ctx = Capstone::new()
                .x86()
                .mode(ArchMode::Mode32)
                .syntax(ArchSyntax::Intel)
                .detail(true)
                .build()
                .expect("Cannot create Capstone context");

            let mut modules = dbi.modules()?;
            while let Some(module) = modules.next()? {
                let Some(module_info) = pdb.module_info(&module)? else {
                    continue;
                };
                let module_info = leak(module_info);

                let program = module_info.line_program()?;
                let mut iter = module_info.symbols()?;

                while let Some(symbol) = iter.next()? {
                    let (name, offset, size) = match symbol.parse() {
                        Ok(pdb2::SymbolData::Procedure(pdb2::ProcedureSymbol {
                            name,
                            offset,
                            len,
                            ..
                        })) => (name, offset, len),
                        Ok(pdb2::SymbolData::Thunk(pdb2::ThunkSymbol {
                            offset,
                            len,
                            name,
                            ..
                        })) => (name, offset, len.into()),
                        _ => continue,
                    };

                    let mut filename = None;

                    let mut lines = program.lines_for_symbol(offset);
                    // Extracting only a single line should be enough to find a source file.
                    if let Some(line_info) = lines.next()? {
                        let file_info = program.get_file_info(line_info.file_index)?;
                        filename = Some(string_table.get(file_info.name)?);
                    }

                    const VOSTOK_PREFIX: &[u8] = b"c:\\survarium\\sources\\vostok\\";
                    let filename: &'static [u8] = match filename {
                        Some(filename) => match filename.as_bytes().strip_prefix(VOSTOK_PREFIX) {
                            Some(filename) => filename,
                            None => b"msvc_internal\\functions",
                        },
                        // See [2]
                        None => continue,
                    };

                    // if ![
                    //     // b"vostok::ai::planning::search_backward::search_backward".as_slice(),
                    //     // b"vostok::ai::planning::search_forward::search_forward".as_slice(),
                    //     // b"survarium::network_client::process_sync_response"
                    //     // vostok::sound::sound_debug_stats::draw_overall_stats"
                    //     // vostok::ai::damage_sensor_parameters::damage_sensor_parameters"
                    // ]
                    // .contains(&name.as_bytes())
                    // {
                    //     continue;
                    // }

                    //
                    //
                    //

                    let fun_offset_in_text = offset.offset as usize;
                    let fun_size = size as usize;

                    let fun_range_in_text = fun_offset_in_text..fun_offset_in_text + fun_size;
                    let fun_va = text.address + fun_offset_in_text;

                    let mut fun_bytes = text_sec_data[fun_range_in_text.clone()].to_vec();
                    let mut offset_in_fun = 0;

                    let ixs =
                        ctx.disasm_all(&text_sec_data[fun_range_in_text.clone()], fun_va as u64)?;
                    for ix in ixs.iter() {
                        let detail = ctx.insn_detail(ix)?;
                        let arch_detail = detail.arch_detail();

                        let groups = detail.groups().iter().map(|v| u32::from(v.0));

                        let is_branch = groups.clone().any(|v| v == CS_GRP_BRANCH_RELATIVE);

                        if !is_branch {
                            offset_in_fun += ix.len();
                            continue;
                        }

                        let ops = arch_detail.operands();
                        assert_eq!(ops.len(), 1);

                        let ArchOperand::X86Operand(X86Operand {
                            op_type: X86OperandType::Imm(target_va),
                            ..
                        }) = ops[0]
                        else {
                            unreachable!()
                        };
                        let internal_branch =
                            (fun_va..fun_va + fun_size).contains(&(target_va as usize));
                        if internal_branch {
                            offset_in_fun += ix.len();
                            continue;
                        }

                        // sushi@TODO: Closest if jumps in the middle of the function
                        match functions.get(&(target_va as usize - text.address)) {
                            Some(overloads) if ix.len() > 4 => {
                                offset_in_fun += ix.len() - 4;
                                fun_bytes[offset_in_fun..offset_in_fun + 4]
                                    .copy_from_slice(&0_u32.to_le_bytes());

                                let result = text_relocs.insert(
                                    fun_offset_in_text + offset_in_fun,
                                    RelocKind::Function { overloads },
                                );
                                offset_in_fun += 4;
                                // @TODO
                                if let Some(result) = result {
                                    let RelocKind::Function {
                                        overloads: old_overloads,
                                    } = result
                                    else {
                                        unreachable!();
                                    };
                                    assert_eq!(overloads.as_ptr(), old_overloads.as_ptr());
                                }
                            }
                            // This usually covers data which is not meant to be instructions.
                            Some(_) | None => {
                                offset_in_fun += ix.len();
                            }
                        }
                    }

                    //
                    //
                    //

                    let object_file = object_files.objects.entry(filename).or_insert_with(|| {
                        let mut object = object::write::Object::new(
                            object::BinaryFormat::Coff,
                            object::Architecture::I386,
                            object::Endianness::Little,
                        );

                        let data_section_id =
                            object.add_section(vec![], b".data".into(), SectionKind::Data);
                        let rdata_section_id =
                            object.add_section(vec![], b".rdata".into(), SectionKind::ReadOnlyData);
                        let text_section_id =
                            object.add_section(vec![], b".text".into(), SectionKind::Text);

                        ObjectFile {
                            object,
                            data_section_id,
                            rdata_section_id,
                            text_section_id,
                        }
                    });

                    let ObjectFile {
                        object,
                        data_section_id: _,
                        rdata_section_id,
                        text_section_id,
                    } = object_file;

                    let fun_offset_in_coff =
                        append_with_padding(object, *text_section_id, &fun_bytes, 0x90);

                    for (reloc_offset_in_text, reloc_kind) in text_relocs.range(fun_range_in_text) {
                        let reloc_offset_in_text = *reloc_offset_in_text as u64;
                        match reloc_kind {
                            RelocKind::Static { symbol: reloc_name } => {
                                let reloc_symbol = object.add_symbol(object::write::Symbol {
                                    name: reloc_name.as_bytes().to_vec(),
                                    value: 0,
                                    size: u64::MAX,
                                    kind: object::SymbolKind::Unknown,
                                    scope: object::SymbolScope::Linkage,
                                    weak: false,
                                    section: object::write::SymbolSection::Undefined,
                                    flags: object::SymbolFlags::None,
                                });

                                let reloc_offset_in_fun =
                                    reloc_offset_in_text - fun_offset_in_text as u64;
                                object.add_relocation(
                                    *text_section_id,
                                    object::write::Relocation {
                                        offset: fun_offset_in_coff + reloc_offset_in_fun,
                                        symbol: reloc_symbol,
                                        addend: -4,
                                        //  zedddie@FIXME: ^^ this seem to be true only for movs/jmps, not for pushes
                                        flags: object::RelocationFlags::Generic {
                                            kind: object::RelocationKind::Relative,
                                            encoding: object::RelocationEncoding::Generic,
                                            size: 32,
                                        },
                                    },
                                )?;
                            }
                            RelocKind::Function { overloads } => {
                                let reloc_name = overloads[0]; // sushi@TODO: Choose the closest match

                                let reloc_symbol = object.add_symbol(object::write::Symbol {
                                    name: reloc_name.as_bytes().to_vec(),
                                    value: 0,
                                    size: u64::MAX,
                                    kind: object::SymbolKind::Unknown,
                                    scope: object::SymbolScope::Linkage,
                                    weak: false,
                                    section: object::write::SymbolSection::Undefined,
                                    flags: object::SymbolFlags::None,
                                });

                                let reloc_offset_in_fun =
                                    reloc_offset_in_text - fun_offset_in_text as u64;
                                object.add_relocation(
                                    *text_section_id,
                                    object::write::Relocation {
                                        offset: fun_offset_in_coff + reloc_offset_in_fun,
                                        symbol: reloc_symbol,
                                        addend: -4,
                                        //  zedddie@FIXME: ^^ this seem to be true only for movs/jmps, not for pushes
                                        flags: object::RelocationFlags::Generic {
                                            kind: object::RelocationKind::Relative,
                                            encoding: object::RelocationEncoding::Generic,
                                            size: 32,
                                        },
                                    },
                                )?;
                            }
                            RelocKind::ConstantValue { data } => {
                                // sushi@TODO: data might be reloc as well, so needs to be handled properly
                                let reloc_name =
                                    format!("value_0x{:x?}", u32::from_le_bytes(*data));

                                let const_offset_in_coff =
                                    append_with_padding(object, *rdata_section_id, data, 0x00);

                                let reloc_symbol = object.add_symbol(object::write::Symbol {
                                    name: reloc_name.as_bytes().to_vec(),
                                    value: const_offset_in_coff,
                                    size: u64::MAX,
                                    kind: object::SymbolKind::Data,
                                    scope: object::SymbolScope::Linkage,
                                    weak: false,
                                    section: object::write::SymbolSection::Section(
                                        *rdata_section_id,
                                    ),
                                    flags: object::SymbolFlags::None,
                                });

                                let reloc_offset_in_fun =
                                    reloc_offset_in_text - fun_offset_in_text as u64;
                                object.add_relocation(
                                    *text_section_id,
                                    object::write::Relocation {
                                        offset: fun_offset_in_coff + reloc_offset_in_fun,
                                        symbol: reloc_symbol,
                                        addend: -4,
                                        //  zedddie@FIXME: ^^ this seem to be true only for movs/jmps, not for pushes
                                        flags: object::RelocationFlags::Generic {
                                            kind: object::RelocationKind::Relative,
                                            encoding: object::RelocationEncoding::Generic,
                                            size: 32,
                                        },
                                    },
                                )?;
                            }
                            RelocKind::ConstantString { symbol, data } => {
                                let reloc_name = match () {
                                    () if symbol.as_bytes().starts_with(b"??_C@_0") => data
                                        .iter()
                                        .copied()
                                        .map(|c| match c.is_ascii_alphanumeric() {
                                            true => c,
                                            false => b'_',
                                        })
                                        .collect::<Vec<_>>(),
                                    () if symbol.as_bytes().starts_with(b"??_C@_1") => data
                                        .windows(2)
                                        .map(|c| {
                                            match c[0] == b'0' && c[1].is_ascii_alphanumeric() {
                                                true => c[1],
                                                false => b'_',
                                            }
                                        })
                                        .collect::<Vec<_>>(),
                                    () => unreachable!(),
                                };

                                let const_offset_in_coff =
                                    append_with_padding(object, *rdata_section_id, data, 0x00);

                                let reloc_symbol = object.add_symbol(object::write::Symbol {
                                    name: reloc_name,
                                    value: const_offset_in_coff,
                                    size: u64::MAX,
                                    kind: object::SymbolKind::Data,
                                    scope: object::SymbolScope::Linkage,
                                    weak: false,
                                    section: object::write::SymbolSection::Section(
                                        *rdata_section_id,
                                    ),
                                    flags: object::SymbolFlags::None,
                                });

                                let reloc_offset_in_fun =
                                    reloc_offset_in_text - fun_offset_in_text as u64;
                                object.add_relocation(
                                    *text_section_id,
                                    object::write::Relocation {
                                        offset: fun_offset_in_coff + reloc_offset_in_fun,
                                        symbol: reloc_symbol,
                                        addend: -4,
                                        //  zedddie@FIXME: ^^ this seem to be true only for movs/jmps, not for pushes
                                        flags: object::RelocationFlags::Generic {
                                            kind: object::RelocationKind::Relative,
                                            encoding: object::RelocationEncoding::Generic,
                                            size: 32,
                                        },
                                    },
                                )?;
                            }
                        }
                    }

                    object.add_symbol(object::write::Symbol {
                        // sushi@TODO: closest symbol to name
                        name: functions
                            .get(&fun_offset_in_text)
                            .map(|fun| fun[0])
                            .unwrap_or(name)
                            .as_bytes()
                            .to_vec(),
                        value: fun_offset_in_coff,
                        size: u64::MAX,
                        kind: object::SymbolKind::Text,
                        scope: object::SymbolScope::Linkage,
                        weak: false,
                        section: object::write::SymbolSection::Section(*text_section_id),
                        flags: object::SymbolFlags::None,
                    });
                }
            }
        }

        Ok(object_files)
    }

    fn write(self, base: &std::path::Path) -> anyhow::Result<()> {
        let base_len = base.as_os_str().as_encoded_bytes().len();
        let mut path = base.to_path_buf();

        for (prefix, object_file) in self.objects {
            path.as_mut_os_string().truncate(base_len);

            path.push(std::str::from_utf8(prefix)?);
            path.as_mut_os_string().push(".obj");

            std::fs::create_dir_all(path.parent().unwrap())?;
            std::fs::write(&path, object_file.object.write()?)?;
        }
        Ok(())
    }
}

// Most of those leaks have to exist to "leak" Streams which for some reason are owning in pdb crate.
fn leak<T>(object: T) -> &'static T {
    Box::leak(Box::new(object))
}

// Always pads to 4
fn append_with_padding(
    object: &mut object::write::Object,
    section_id: object::write::SectionId,
    data: &[u8],
    pad: u8,
) -> u64 {
    let offset = object.append_section_data(section_id, data, 1);

    // sushi@TODO: `object` crate doesn't(?) allow specifying auxiliary symbols.
    // Because of that 1-3 bytes of garbage are generated which objdiff doesn't like.
    // We replace those bytes with `nop`s and pad all of the functions ourselves,
    // which fixes the problem, but this is a hack, which needs to be fixed at some point.
    let padding: &[u8] = match 4 - data.len() % 4 {
        1 => &[pad],
        2 => &[pad, pad],
        3 => &[pad, pad, pad],
        _ => &[],
    };
    if !padding.is_empty() {
        _ = object.append_section_data(section_id, padding, 1);
    }

    offset
}
